version: '3'
services:
  movies_elasticsearch:
    image: elasticsearch:7.17.6
    container_name: movies_elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./src/database:/usr/share/elasticsearch/data
    restart: always

  movies_redis:
    container_name: movies_redis
    image: redis
    hostname: movies_redis
    restart: always

  movies_api:
    container_name: movies_api
    build:
      context: ./src/
      dockerfile: DockerFile
    hostname: movies_api
    volumes:
      - ./src:/app
    depends_on:
      - movies_elasticsearch
      - movies_redis
    restart: always

  auth_db:
    image: postgres:13
    restart: always
    container_name: auth_db
    volumes:
      - ./flask_app/database/data/:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: qwe
      POSTGRES_USER: app
      POSTGRES_DB: movies_database

  auth_cache:
    container_name: auth_cache
    image: redis
    hostname: auth_cache
    restart: always

  auth_api:
    build:
      context: ./flask_app/
      dockerfile: DockerFile
    container_name: auth_api
    depends_on:
      - auth_db
      - auth_cache
    env_file:
      - ./flask_app/.env
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
    depends_on:
      - auth_api
      - movies_api
    ports:
      - "80:80"
    restart: always

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - 6831:6831/udp
      - 16686:16686
    depends_on:
      - nginx
    restart: always